### ISSUE TITLE
HTML formatted E-mail?

### ISSUE THREAD

**Issue by anmolsahoo25** [socketlabs/wordpress#1]
Is there some configuration required for sending out html formatted email? 

All my emails are being sent as plain-text through this plugin.

**Comment by msoler8785** [comment]
There is no setting in the plugin to set the content type directly. The content type is usually controlled by the theme or by another plugin.  

The SocketLabs plugin will default to `text/html`. If all of the emails are being sent as `text/plain` then the theme or another plugin could be setting the headers directly. There are two primary ways this could be done.

1. By setting the Content-Type directly:

```php
$to = 'sendto@example.com';
$subject = 'The subject';
$body = 'The email body content';
$headers = array('Content-Type: text/html; charset=UTF-8');
wp_mail( $to, $subject, $body, $headers );
```
2. By creating a filter for the wordpress wp_mail_content_type hook. https://developer.wordpress.org/reference/hooks/wp_mail_content_type/
